name: build manylinux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build in manylinux container
      run: docker run --rm -v `pwd`:/repo --rm safijari/manylinux2010-x64 /repo/run_build.sh
    - name: Tar up artifacts
      run: tar -czf dist.tar.gz dist/
    - uses: actions/upload-artifact@master
      with:
        name: dist
        path: dist/
